# Generated by Django 4.2 on 2024-02-03 08:21

import datetime
from django.db import migrations, models
import pawgoapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default=pawgoapp.models.generate_code, max_length=12)),
                ('value', models.IntegerField(default=0)),
                ('expiration_date', models.DateTimeField(default=datetime.datetime(2024, 2, 13, 8, 21, 38, 913485, tzinfo=datetime.timezone.utc))),
                ('isused', models.BooleanField(default=False)),
            ],
        ),
    ]
