# Generated by Django 4.2 on 2024-02-03 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawgoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topup',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 8, 46, 11, 420339, tzinfo=datetime.timezone.utc)),
        ),
    ]
