# Generated by Django 4.2 on 2024-02-03 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawgoapp', '0003_topup_value_currency_alter_topup_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topup',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 10, 6, 28, 723317, tzinfo=datetime.timezone.utc)),
        ),
    ]
