# Generated by Django 5.0.1 on 2024-02-02 03:22

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name=datetime.datetime(2024, 2, 2, 3, 22, 0, 301881, tzinfo=datetime.timezone.utc))),
                ('text', models.CharField(max_length=512)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_post', to=settings.AUTH_USER_MODEL)),
                ('walker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_blame', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
