# Generated by Django 5.0.1 on 2024-02-02 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispute',
            old_name='text',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='dispute',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 2, 2, 3, 52, 37, 524528, tzinfo=datetime.timezone.utc)),
        ),
    ]
