# Generated by Django 5.0.1 on 2024-02-02 04:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0003_alter_dispute_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
