# Generated by Django 5.0.1 on 2024-02-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0004_alter_dispute_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='ishandled',
            field=models.BooleanField(default=False),
        ),
    ]
